### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by adis-me** [GIVESocialMovement/sbt-i18n#10]
In the README you have stated to included the following plugin:

```
addSbtPlugin("givers.vuefy" % "sbt-i18n" % "3.0.0")
```

But I think this should be:

```
addSbtPlugin("givers.i18n" % "sbt-i18n" % "3.0.0")
```

`givers.i18n` instead of `givers.vuefy`. Otherwise you will get a lot of errors complaining about unresolved deps.

**Comment by tanin47** [comment]
Thank you @adis-me. Fixed.

Please don't hesitate to let me know if you encounter an issue using it.

Thank you again for reporting this issue.
